kind: dataset/annotation/csv
name: openpack-outliers
metadata:
  labels:
    type: annotation/outlier
    version: v1.4.0
    dependency: null
    resolution: original
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/annotation/openpack-outliers
    fname: ${session}.csv
  file:
    columns:
    - uuid: UUID
      dtype: str
    - name: user
      dtype: str
    - name: session
      dtype: str
    - name: box
      dtype: int
    - name: id
      dtype: str
    - name: category
      dtype: str
    - name: event
      dtype: str
    - name: start
      dtype: datetime
    - name: end
      dtype: datetime
    - name: tags
      dtype: List[str]
  classes:
  - id: Aa01
    category: Incident
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
    - Single
  - id: Aa02
    category: Incident
    event: Miss
    description: A worker makes a mistake.
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
    - Single
  - id: Aa03
    category: Incident
    event: Accident
    description: A worker suffers from an accident.
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
    - Single
  - id: Aa04
    category: Incident
    event: System Error
    description: Problems occurred in the experimental environment or in the sensors
      device side.
    version: v1.4.0
    ignore: false
  - id: Aa05
    category: Incident
    event: Talk to Staff
    description: Talking to staff to inform of problems they faced. For example, box
      stock is runnning out.
    version: v1.4.0
    ignore: false
  - id: Aa06
    category: Incident
    event: Break Label
    description: The item label is broken when it is peeled off.
    version: v1.4.0
    ignore: false
  - id: Aa07
    category: Incident
    event: Wrong Choice of Box Size
    description: A worker is picking up a box that is not sufficiently large to put
      all the items in it.
    version: v1.4.0
    ignore: false
    tags:
    - S
    - M
    - L
    - LL
  - id: Ab01
    category: Investigation
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Ab02
    category: Investigation
    event: System Error
    description: Checking sensor devices or tools such as handheld scanners.
    version: v1.4.0
    ignore: false
  - id: Ab03
    category: Investigation
    event: Check Box Size
    description: Checking to see if all the items fit into the box by, for example,
      placing the item to the side of the box.
    version: v1.4.0
    ignore: false
    tags:
    - Item
    - Box-Close
    - Box-Open
    - Box-In
  - id: Ab04
    category: Investigation
    event: Check Item Size
    description: Holding items to see their sizes.
    version: v1.4.0
    ignore: false
  - id: Ab05
    category: Investigation
    event: Talk to Staff
    description: Stopping their work and asking how they can recover from mistakes
      or accidents.
    version: v1.4.0
    ignore: false
  - id: Ac01
    category: Recovery
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Ac02
    category: Recovery
    event: System Error
    description: Fixing device errors etc.
    version: v1.4.0
    ignore: false
  - id: Ac03
    category: Recovery
    event: Take out Inserted Items from Box
    description: Taking out items from the box to change to a different size box.
    version: v1.4.0
    ignore: false
  - id: Ac04
    category: Recovery
    event: Put Away Box for Resizing
    description: Moving the box to the side of the workbench to discard the box which
      is of the wrong size.
    version: v1.4.0
    ignore: false
    tags:
    - S
    - M
    - L
    - LL
  - id: Ac05
    category: Recovery
    event: Disassemble Box for Resizing
    description: Removing the attached tapes and disassembling box to use a different
      sized box
    version: v1.4.0
    ignore: false
    tags:
    - S
    - M
    - L
    - LL
  - id: Ac06
    category: Recovery
    event: Fold Box to Clean Up
    description: Fold the box back into the stock before the `bend flap` operation.
    version: v1.4.0
    ignore: false
  - id: Ac07
    category: Recovery
    event: Return Box
    description: Put the folded box on the box stock.
    version: v1.4.0
    ignore: false
  - id: Ac08
    category: Recovery
    event: Talk to Staff
    description: Correcting their mistakes while asking the staff what to do.
    version: v1.4.0
    ignore: false
  - id: Ac09
    category: Recovery
    event: Item Label
    description: Correction of errors related to the attachment and removal of item
      labels.
    version: v1.4.0
    ignore: false
  - id: Bx01
    category: Struggling
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Bx02
    category: Struggling
    event: Look for Items
    description: Stopping in front of the back table and looking for items to pack.
    version: v1.4.0
    ignore: false
  - id: Bx03
    category: Struggling
    event: Label
    description: Struggling to remove the labels.
    version: v1.4.0
    ignore: false
    tags:
    - Item
    - Box
    - Shipping
  - id: Bx04
    category: Struggling
    event: Scan
    description: Struggling to scan labels.
    version: v1.4.0
    ignore: false
    tags:
    - HT
    - LP
  - id: Bx05
    category: Struggling
    event: Air Cushion
    description: Struggling to cut air cushion, or  struggling to put air cushions
      into the box.
    version: v1.4.0
    ignore: false
  - id: Bx06
    category: Struggling
    event: Insert Items
    description: Struggling to insert items into the box.
    version: v1.4.0
    ignore: false
  - id: Bx07
    category: Struggling
    event: Tape
    description: Struggling to attach tape to the box.
    version: v1.4.0
    ignore: false
  - id: Cx01
    category: Confused
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Cx02
    category: Confused
    event: Box Size
    description: Stop their movements and think about which box size to pick.
    version: v1.4.0
    ignore: false
  - id: Cx04
    category: Confused
    event: Process
    description: Almost doing something else that is out of the expected work procedure.
    version: v1.4.0
    ignore: false
  - id: Cx05
    category: Confused
    event: Double Check
    description: Double check by pointing items with their finger.
    version: v1.4.0
    ignore: false
  - id: Dx01
    category: Parallel
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Dx02
    category: Parallel
    event: Action&Action
    description: Overlap of two `action` labels.
    version: v1.4.0
    ignore: false
    tags:
    - 0101*1003
    - 0108*0201
    - 0302*0303
    - 0303*0304
    - 0303*0401
    - 0303*0501
    - 0401*0403
    - 0706*1001
    - 0707*1001
    - 0801*1003
    - 1002*1003
  - id: Dx03
    category: Parallel
    event: Action&Additional
    description: Overlap of an `action` label and an `outlier/additional` label.
    version: v1.4.0
    ignore: false
    tags:
    - 0101*G06
    - 0108*G06
    - 0301*B03
    - 0301*G05
    - 0301*G06
    - 0303*0304*G07
    - 0303*G06
    - 0304*G07
    - 0401*G07
    - 0401*G08
    - 0502*G07
    - 0502*G08
    - 0601*G03
    - 0601*G08
    - 0701*G06
    - 0701*G08
    - 0702*G06
    - 0703*G08
    - 0704*G08
    - 0707*G06
    - 0707*G08
    - 0801*G03
    - 0801*G06
    - 0801*G08
    - 0901*G06
    - 1001*G06
    - 1003*G06
  - id: Dx04
    category: Parallel
    event: Action&Others
    description: Overlap of an `action` label and an `other` label in any category.
    version: v1.4.0
    ignore: false
    tags:
    - '107'
    - '030'
    - '109'
    - '011'
    - '001'
  - id: Dx05
    category: Parallel
    event: Additional&Additional
    description: Overlap of two `outlier/additional` labels.
    version: v1.4.0
    ignore: false
    tags:
    - B01*G07
    - C03*C04
    - G06*G08
    - G03*G06
  - id: Dx06
    category: Parallel
    event: Additional&Others
    description: Overlap of an `outlier/additional` label and an `other` label/s.
    version: v1.4.0
    ignore: false
  - id: Ex01
    category: Additional
    event: Others
    description: (no specific events)
    version: v1.4.0
    ignore: false
    tags:
    - LOW
    - HIGH
  - id: Ex02
    category: Additional
    event: Talk to Staff
    description: Stopping their work and talking with staff.
    version: v1.4.0
    ignore: false
  - id: Ex03
    category: Additional
    event: Dispose
    description: Discarding the trash of box labels.
    version: v1.4.0
    ignore: false
  - id: Ex05
    category: Additional
    event: Refill Boxe Stock
    description: Move additional box stock to the workbench.
    version: v1.4.0
    ignore: false
    tags:
    - S-D
    - S
    - M
    - L
    - LL
  - id: Ex06
    category: Additional
    event: Clean Up the Workbench
    description: Clean up the workbench. For example, organizing order sheets.
    version: v1.4.0
    ignore: false
  - id: Ex07
    category: Additional
    event: Lift Up Box
    description: Lifting up the assembled box.
    version: v1.4.0
    ignore: false
  - id: Ex08
    category: Additional
    event: Move Box
    description: Turning and moving the assembled box on the workbench.
    version: v1.4.0
    ignore: false
