kind: dataset/annotation/csv
name: openpack-actions
metadata:
  labels:
    type: annotation/action
    version: v3.5.0
    dependency: null
    resolution: original
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/annotation/openpack-actions
    fname: ${session}.csv
  file:
    columns:
    - uuid: UUID
      dtype: str
    - name: user
      dtype: str
    - name: session
      dtype: str
    - name: box
      dtype: int
    - name: id
      dtype: int
    - name: operation
      dtype: str
    - name: action
      dtype: str
    - name: start
      dtype: datetime
    - name: end
      dtype: datetime
    - name: box_size
      dtype: str
    - name: work_position
      dtype: str
  classes:
  - id: 101
    operation: Picking
    name: Pick Up Sheet
    description: Pick up order sheet from the workbench.
    version: v3.2.2
    ignore: false
  - id: 103
    operation: Picking
    name: Pick Up Item from Box
    description: Pick items out of a box that contains items picked in batches.
    version: v3.2.2
    ignore: false
  - id: 107
    operation: Picking
    name: Pick Up Box Sheet
    description: Pick up an order sheet and packed boxes at the same time. (This label
      is used for moving packed boxes and picking items for the next box at the same
      time.)
    version: v3.2.2
    ignore: false
  - id: 108
    operation: Picking
    name: Walk to Work Bench
    description: Lift the item and turn back toward the workbench. (When picking is
      done in one round trip, this action is set as the beginning of the box.)
    version: v3.2.2
    ignore: false
  - id: 109
    operation: Picking
    name: Put Packed Box
    description: Go to the back table and place the packed box under the table.
    version: v3.3.0
    ignore: false
  - id: 201
    operation: Relocate Item Label
    name: Remove Item Label
    description: Remove the sticker with the barcode from the each item.
    version: v3.2.2
    ignore: false
  - id: 202
    operation: Relocate Item Label
    name: Attach to Order Sheet
    description: Attach the label on the bottom margin of the order sheet.
    version: v3.2.2
    ignore: false
  - id: 203
    operation: Relocate Item Label
    name: Hold Pen
    description: ''
    version: v3.2.2
    ignore: false
  - id: 204
    operation: Relocate Item Label
    name: Write Check Mark
    description: 'The subject''s checkes items name and quantity. '
    version: v3.2.2
    ignore: false
  - id: 205
    operation: Relocate Item Label
    name: Put Item Small Bag
    description: Insert small items (<10cm) into the small paper bag and close it
      with tape. The action is almost the same as ID0404 but the timing is different.
    version: v3.4.0
    ignore: false
  - id: 301
    operation: Assemble Box
    name: Pick Cardboard
    description: Select and pick up boxes that match the size of the items.
    version: v3.2.2
    ignore: false
  - id: 302
    operation: Assemble Box
    name: Bend Flap
    description: Bend "bottom" 4 flaps of the box.
    version: v3.2.2
    ignore: false
  - id: 303
    operation: Assemble Box
    name: Attach Tape
    description: Apply craft tape to close the "bottom" of the box.
    version: v3.2.2
    ignore: false
  - id: 304
    operation: Assemble Box
    name: Turn Over Box
    description: Turn the box upside down so that the side with the craft tape is
      on the bottom.
    version: v3.2.2
    ignore: false
  - id: 305
    operation: Assemble Box
    name: Pick Up Assembled Box
    description: Pick up a pre-assembled box. (Used in Scenario.3-5)
    version: v3.2.2
    ignore: false
  - id: 401
    operation: Insert Items
    name: Insert Item into Box
    description: Subject grabs individual items and inserts them in the assembled
      box
    version: v3.2.2
    ignore: false
  - id: 402
    operation: Insert Items
    name: Air Cushion
    description: Insert air cushion to the box.
    version: v3.2.2
    ignore: false
  - id: 403
    operation: Insert Items
    name: Separate Air Cushion
    description: Tear off the connected cushioning.
    version: v3.2.2
    ignore: false
  - id: 404
    operation: Insert Items
    name: Put Item Small Bag
    description: Insert small items (<10cm) into the small paper bag and close it
      with tape. The action is almost the same as ID0205 but the timing is different.
    version: v3.4.0
    ignore: false
  - id: 501
    operation: Close Box
    name: Bend Flap
    description: Bend 4 flaps in the upper side of the box.
    version: v3.2.2
    ignore: false
  - id: 502
    operation: Close Box
    name: Attach Tape
    description: Close the box with craft tape.
    version: v3.2.2
    ignore: false
  - id: 601
    operation: Attach Box Label
    name: Attach Box Label
    description: Place the box number label on the side of the box.
    version: v3.2.2
    ignore: false
  - id: 701
    operation: Scan Label
    name: Pick Up HT
    description: Pick up handy scanner (HT).
    version: v3.2.2
    ignore: false
  - id: 702
    operation: Scan Label
    name: Scan Order Sheet
    description: Scan the order ID code in the upper left corner of the order sheet.
    version: v3.2.2
    ignore: false
  - id: 703
    operation: Scan Label
    name: Scan Box
    description: Scan  the box number label.
    version: v3.2.2
    ignore: false
  - id: 704
    operation: Scan Label
    name: Scan Item
    description: Scan each item number on the label on the order sheet one by one.
    version: v3.2.2
    ignore: false
  - id: 705
    operation: Scan Label
    name: Hold Scanner
    description: Pick up white scanner (for label printer).
    version: v3.2.2
    ignore: false
  - id: 706
    operation: Scan Label
    name: Scan Order Sheet
    description: Scan the order ID code in the upper left corner of the order sheet
      with the white scanner.
    version: v3.2.2
    ignore: false
  - id: 707
    operation: Scan Label
    name: Scan Printer
    description: Scan the code on the label printer to print out sheiiping labels.
    version: v3.2.2
    ignore: false
  - id: 801
    operation: Attach Shipping Label
    name: Pick Up Shipping Label
    description: Pick up shipping label from the label printer.
    version: v3.2.2
    ignore: false
  - id: 802
    operation: Attach Shipping Label
    name: Attach Shipping Label
    description: Attach the printed shipping label to the upper side of the box.
    version: v3.2.2
    ignore: false
  - id: 901
    operation: Put on Back Table
    name: Pick Up Packed Box
    description: Pick up prepared box from the workbench.
    version: v3.2.2
    ignore: false
  - id: 902
    operation: Put on Back Table
    name: Put Packed Box
    description: Go to the back table and place the packed box under the table.
    version: v3.2.2
    ignore: false
  - id: 1001
    operation: Fill out Order
    name: Pick Up Pen
    description: The subject's hand touches the pen.
    version: v3.2.2
    ignore: false
  - id: 1002
    operation: Fill out Order
    name: Write Sign
    description: Sign each field in the column next to the item list on the order
      sheet.
    version: v3.2.2
    ignore: false
  - id: 1003
    operation: Fill out Order
    name: Push Order Sheet into Tray
    description: Insert order sheet into the tray for completed order sheets.
    version: v3.2.2
    ignore: false
  - id: 8101
    operation: 'Null'
    name: Others
    description: ''
    version: v3.2.2
    ignore: true
  - id: 8102
    operation: 'Null'
    name: System Error
    description: ''
    version: v3.2.2
    ignore: true
  - id: 8103
    operation: 'Null'
    name: Ignore
    description: ''
    version: v3.2.2
    ignore: true
  - id: 8104
    operation: 'Null'
    name: Unknown
    description: ''
    version: v3.2.2
    ignore: true
  - id: 8105
    operation: 'Null'
    name: 'Null'
    description: Segment without any specific actions. This class is prepared for
      action detection.
    version: v3.5.0
    ignore: false
  - id: 8106
    operation: 'Null'
    name: Exclude
    description: Segments with this label should be excluded from evaluation. This
      class is prepared for action detection.
    version: v3.5.0
    ignore: true
  - id: 8201
    operation: System Error
    name: System Error
    description: ''
    version: v3.2.2
    ignore: true
