kind: dataset/stream/imu
name: atr-acc
mdetadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: IMU/Acc
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/atr
    fname: ${device}/${session}.csv
  devices:
    - atr01
    - atr02
    - atr03
    - atr04
  acc: true
  gyro: false
  quat: false
  frameRate: 30
