kind: dataset/stream/imu
name: atr-qags
mdetadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: IMU
    sensorProductName: ATR TSND151
    sensorProdcutReference: http://www.atr-p.com/products/TSND121_151.html
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/atr
    fname: ${device}/${session}.csv
  devices:
  - atr01
  - atr02
  - atr03
  - atr04
  acc: true
  gyro: true
  quat: true
  frameRate: 30
  fileFormat:
    fileType: csv
    columns:
    - name: unixtime
      unit: milli second
    - name: acc_x
      unit: G
    - name: acc_y
      unit: G
    - name: acc_z
      unit: G
    - name: gyro_x
      unit: dps
    - name: gyro_y
      unit: dps
    - name: gyro_z
      unit: dps
    - name: quat_w
    - name: quat_x
    - name: quat_y
    - name: quat_z
