kind: dataset/stream/e4
name: e4-acc
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: ACC
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/acc
    fname: ${session}.csv
    template: ${.dir}/${.fname}
  devices:
  - e401
  - e402
  frameRate: 32
  fileFormat:
    fileType: csv
    columns:
    - name: time
      unit: milli second
    - name: acc_x
      unit: G
    - name: acc_y
      unit: G
    - name: acc_z
      unit: G
  sensor: e4
  sensorProduct:
    name: Empatica E4
    uri: https://www.empatica.com/en-int/research/e4/
