kind: dataset/stream/e4
name: e4-bvp
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensor: e4
    sensorType: Blood Volume Pulse (BVP)
    sensorProductName: Empatica E4
    sensorProdcutReference: https://www.empatica.com/en-int/research/e4/
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/bvp
    fname: ${session}.csv
    template: ${.dir}/${.fname}
  devices:
  - e401
  - e402
  frameRate: 64
  fileFormat:
    fileType: csv
    columns:
    - name: time
      unit: milli second
    - name: bvp
      unit: mmHg
