kind: dataset/stream/e4
name: e4-bvp
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: Blood Volume Pulse (BVP)
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/bvp
    fname: ${session}.csv
    template: ${.dir}/${.fname}
  devices:
  - e401
  - e402
  frameRate: 64
  fileFormat:
    fileType: csv
    columns:
    - name: time
      unit: milli second
    - name: bvp
      unit: mmHg
  sensor: e4
  sensorProduct:
    name: Empatica E4
    uri: https://www.empatica.com/en-int/research/e4/
