kind: dataset/stream
name: e4-eda
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensor: e4
    sensorType: EDA
    sensorProductName: Empatica E4
    sensorProdcutReference: https://www.empatica.com/en-int/research/e4/
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/eda
    fname: ${session}.csv
    template: ${.dir}/${.fname}
  devices:
  - e401
  - e402
  fileFormat:
    fileType: csv
    columns:
    - name: time
      unit: milli second
    - name: eda
      unit: microsiemens
  frameRate: 4
