kind: dataset/stream/e4
name: e4-temp
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensor: e4
    sensorType: temperature
    sensorProductName: Empatica E4
    sensorProdcutReference: https://www.empatica.com/en-int/research/e4/
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/temp
    fname: ${session}.csv
    template: ${.dir}/${.fname}
  devices:
  - e401
  - e402
  frameRate: 4
  fileFormat:
    fileType: csv
    columns:
    - name: time
      unit: milli second
    - name: temp
      unit: microsiemens
