kind: dataset/stream/image
name: kinect-depth
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: depth/16bit-png
    view: front-view
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/kinect/depth/frames
    fname: ${session}
  fileFormat:
    fileType: 16bit Grayscal PNG
    pathFormat: '%Y/%m/%d/%H/%M/%Y%m%d_%H%M%S_%f.png'
    imageSize:
      width: 640
      height: 576
  frameRate: 15
  sensorProduct:
    name: Azure Kinect DK
    uri: https://azure.microsoft.com/ja-jp/products/kinect-dk/
  preprocessing:
    - name: Coordinate Transoformation
      model: k4a_transformation_depth_image_to_color_camera()
      uri: https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_gafacffb5f781a9c2df30d4a16241cd514.html
