kind: dataset/stream/keypoint
name: kinect-3d-kpt
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorProdcutName: Azure Kinect DK
    sensorProdcutReference: https://azure.microsoft.com/ja-jp/products/kinect-dk/
    keypointType: 3d
    poseEstimationModel: k4abt
    sdkUrl: https://learn.microsoft.com/ja-jp/azure/kinect-dk/build-first-body-app
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/kinect/3d-kpt/${...metadata.labels.poseEstimationModel}/${preprocessing}
    fname: ${session}.json
  preprocessings:
  - none
  - single-ffill
  - single-ffill-flip-fixed
  - unity
  fileFormat:
    fileType: json
    note: MS COCO format
    columns:
    - name: info
      unit: null
      dtype: dict
    - name: licences
      unit: null
      dtype: list[dict]
    - name: annotations
      unit: null
      dtype: list[dict]
    - name: annotations/id
      unit: null
      dtype: int
    - name: annotations/image_id
      unit: milli seconds
      dtype: int
      note: UNIXtime with milli seconds precision
    - name: annotations/category_id
      unit: null
      dtype: int
    - name: annotations/area
      unit: null
      dtype: float
    - name: annotations/bbox
      unit: null
      dtype: Tuple[float, float, float, float]
      note: '[x, y, width, height]'
    - name: annotations/iscrowd
      unit: null
      dtype: int
      note: iscrowd = 0
    - name: annotations/keypoints
      unit: px
      dtype: list[float]
      note: '[x1, y1, v1, ...] (v? = confidence score)'
    - name: annotations/num_keypoints
      unit: null
      dtype: int
    - name: annotations/bbox_score
      unit: null
      dtype: float
      note: confidence score for the bounding box
    - name: annotations/track_id
      unit: null
      dtype: int
    - name: category
      unit: null
      dtype: list
  frameRate: 15
  nodes:
    0: nose
    1: left_eye
    2: right_eye
    3: left_ear
    4: right_ear
    5: left_shoulder
    6: right_shoulder
    7: left_elbow
    8: right_elbow
    9: left_wrist
    10: right_wrist
    11: left_hip
    12: right_hip
    13: left_knee
    14: right_knee
    15: left_ankle
    16: right_ankle
