kind: dataset/stream/image
name: rs02-depth
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: depth/16bit-png
    view: top-view
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/rs02/depth/frames
    fname: ${session}
  fileFormat:
    fileType: 16bit Grayscal PNG
    pathFormat: '%Y/%m/%d/%H/%M/%Y%m%d_%H%M%S_%f.png'
    imageSize:
      width: 640
      height: 480
  frameRate: 15
  sensor: rs02
  sensorProduct:
    name: Realsense
    uri: https://www.intel.com/content/www/us/en/products/sku/190004/intel-realsense-depth-camera-d435i/specifications.html
