kind: dataset/stream/system/ht
name: system-ht-original
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: IoT/handheld-scanner
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/system/ht
    fname: ${session}.csv
  fileFormat:
    fileType: csv
    columns:
    - name: unixtime
      unit: milli second
      dtype: int
    - name: datetime
      unit: null
      dtype: str (ISO format)
    - name: order_sheet
      unit: null
      dtype: str
    - name: box
      unit: null
      dtype: str
    - name: item
      unit: null
      dtype: str
  frameRate: -1
  sensorProduct:
    name: null
    uri: null
