kind: dataset/stream/system
name: system-order-sheet
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: system/order-sheet
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/system/order-sheet/
    fname: ${session}.csv
  fileFormat:
    fileType: csv
    columns:
    - name: sheet_no
      unit: null
      dtype: str
      note: format = DEN{session_no:0=4}{box_no:0=2}
    - name: session
      unit: null
      dtype: str
    - name: box
      unit: null
      dtype: str
    - name: pattern
      unit: null
      dtype: str
    - name: total_amount
      unit: null
      dtype: str
    - name: item1
      unit: null
      dtype: str
    - name: item2
      unit: null
      dtype: str
    - name: item3
      unit: null
      dtype: str
    - name: item4
      unit: null
      dtype: str
    - name: item5
      unit: null
      dtype: str
    - name: amount1
      unit: null
      dtype: str
    - name: amount2
      unit: null
      dtype: str
    - name: amount3
      unit: null
      dtype: str
    - name: amount4
      unit: null
      dtype: str
    - name: amount5
      unit: null
      dtype: str
  frameRate: -1
  sensorProduct:
    name: null
    uri: null
