kind: dataset/stream/system/printer
name: system-printer
metadata:
  labels:
    app: openpack
    version: 1.0.0
    sensorType: IoT/printer (pseudo data)
    sensorProductName: null
    sensorProdcutReference: null
spec:
  path:
    dir: ${path.openpack.rootdir}/${user.name}/system/printer
    fname: ${session}.csv
  fileFormat:
    fileType: csv
    columns:
    - name: unixtime
      unit: milli second
      dtype: int
    - name: datetime
      unit: null
      dtype: str (ISO format)
    - name: order_sheet
      unit: null
      dtype: str
  frameRate: 30
