kind: dataset/split/flexible-train-data-volume
name: benchmark3
metadata:
  labels:
    app: openpack-benchmarks
    benchmarkType: benchmark3
    version: 1.0.0
    params: ${train_set}
spec:
  test:
    # == U0104 ==
    - ["U0104", "S0100"]
    - ["U0104", "S0300"]
    # == U0108 ==
    - ["U0108", "S0100"]
    - ["U0108", "S0200"]
    - ["U0108", "S0300"]
    - ["U0108", "S0500"]
    # == U0110 ==
    - ["U0110", "S0100"]
    - ["U0110", "S0200"]
    - ["U0110", "S0300"]
    - ["U0110", "S0400"]
    - ["U0110", "S0500"]
    # == U0203 ==
    - ["U0203", "S0100"]
    - ["U0203", "S0200"]
    - ["U0203", "S0300"]
    - ["U0203", "S0400"]
    - ["U0203", "S0500"]
    # == U0204 ==
    - ["U0204", "S0200"]
    - ["U0204", "S0300"]
    - ["U0204", "S0400"]
    # == U0207 ==
    - ["U0207", "S0300"]
    - ["U0207", "S0400"]
    - ["U0207", "S0500"]
  pool:
    U0101:
      order: 1 # Remove?
      train:
        - ["U0101", "S0300"]
    U0102:
      order: 2
      train:
        - ["U0102", "S0300"]
    U0103:
      order: 3
      train:
        - ["U0103", "S0300"]
    U0105:
      order: 4
      train:
        - ["U0105", "S0300"]
    U0106:
      order: 5
      train:
        - ["U0106", "S0300"]
    U0107:
      order: 6
      train:
        - ["U0107", "S0300"]
    U0111:
      order: 7
      train:
        - ["U0111", "S0300"]
    U0201:
      order: 8
      train:
        - ["U0201", "S0300"]
    U0202:
      order: 9
      train:
        - ["U0202", "S0300"]
    U0205:
      order: 10
      train:
        - ["U0205", "S0300"]
    U0206:
      order: 11
      train:
        - ["U0206", "S0300"]
    U0208:
      order: 12
      train:
        - ["U0208", "S0300"]
    U0209:
      order: 13
      train:
        - ["U0209", "S0300"]
    U0210:
      order: 14
      train:
        - ["U0210", "S0300"]