kind: dataset/split/data-volume-flexible-cv
name: benchmark2
metadata:
  labels:
    app: openpack-benchmarks
    benchmarkType: benchmark2
    version: 1.0.0
    params: ${target_set}
spec:
  pool:
    U0101:
      train:
        - ["U0101", "S0300"]
      test:
        - ["U0101", "S0100"]
        - ["U0101", "S0200"]
        - ["U0101", "S0400"]
        - ["U0101", "S0500"]
    U0102:
      train:
        - ["U0102", "S0300"]
      test:
        - ["U0102", "S0100"]
        - ["U0102", "S0200"]
        - ["U0102", "S0400"]
        - ["U0102", "S0500"]
    U0103:
      train:
        - ["U0103", "S0300"]
      test:
        - ["U0103", "S0100"]
        - ["U0103", "S0200"]
        - ["U0103", "S0400"]
        - ["U0103", "S0500"]
    U0104:
      train:
        - ["U0104", "S0300"]
      test:
        - ["U0104", "S0100"]
        - ["U0104", "S0200"]
        - ["U0104", "S0400"]
    U0105:
      train:
        - ["U0105", "S0300"]
      test:
        - ["U0105", "S0100"]
        - ["U0105", "S0200"]
        - ["U0105", "S0400"]
        - ["U0105", "S0500"]
    U0106:
      train:
        - ["U0106", "S0300"]
      test:
        - ["U0106", "S0100"]
        - ["U0106", "S0200"]
        - ["U0106", "S0400"]
        - ["U0106", "S0500"]
    U0107:
      train:
        - ["U0107", "S0300"]
      test:
        - ["U0107", "S0100"]
        - ["U0107", "S0200"]
        - ["U0107", "S0400"]
        - ["U0107", "S0500"]
    U0108:
      train:
        - ["U0108", "S0300"]
      test:
        - ["U0108", "S0100"]
        - ["U0108", "S0200"]
        # - ["U0108", "S0400"]
        - ["U0108", "S0500"]
    U0109:
      train:
        - ["U0109", "S0300"]
      test:
        - ["U0109", "S0100"]
        - ["U0109", "S0200"]
        - ["U0109", "S0400"]
        - ["U0109", "S0500"]
    U0110:
      train:
        - ["U0110", "S0300"]
      test:
        - ["U0110", "S0100"]
        - ["U0110", "S0200"]
        - ["U0110", "S0400"]
        - ["U0110", "S0500"]
    U0111:
      train:
        - ["U0111", "S0300"]
      test:
        - ["U0111", "S0100"]
        - ["U0111", "S0200"]
        - ["U0111", "S0400"]
        - ["U0111", "S0500"]
    U0201:
      train:
        - ["U0201", "S0300"]
      test:
        - ["U0201", "S0100"]
        - ["U0201", "S0200"]
        - ["U0201", "S0400"]
        - ["U0201", "S0500"]
    U0202:
      train:
        - ["U0202", "S0300"]
      test:
        - ["U0202", "S0100"]
        - ["U0202", "S0200"]
        - ["U0202", "S0400"]
        - ["U0202", "S0500"]
    U0203:
      train:
        - ["U0203", "S0300"]
      test:
        - ["U0203", "S0100"]
        - ["U0203", "S0200"]
        - ["U0203", "S0400"]
        - ["U0203", "S0500"]
    U0204:
      train:
        - ["U0204", "S0300"]
      test:
        - ["U0204", "S0100"]
        - ["U0204", "S0200"]
        - ["U0204", "S0400"]
        - ["U0204", "S0500"]
    U0205:
      train:
        - ["U0205", "S0300"]
      test:
        - ["U0205", "S0100"]
        - ["U0205", "S0200"]
        - ["U0205", "S0400"]
        - ["U0205", "S0500"]
    U0206:
      train:
        - ["U0206", "S0300"]
      test:
        - ["U0206", "S0100"]
        - ["U0206", "S0200"]
        - ["U0206", "S0400"]
        - ["U0206", "S0500"]
    U0207:
      train:
        - ["U0207", "S0300"]
      test:
        - ["U0207", "S0100"]
        - ["U0207", "S0200"]
        - ["U0207", "S0400"]
        - ["U0207", "S0500"]
    U0208:
      train:
        - ["U0208", "S0300"]
      test:
        - ["U0208", "S0100"]
        - ["U0208", "S0200"]
        - ["U0208", "S0400"]
        - ["U0208", "S0500"]
    U0209:
      train:
        - ["U0209", "S0300"]
      test:
        - ["U0209", "S0100"]
        - ["U0209", "S0200"]
        - ["U0209", "S0400"]
        - ["U0209", "S0500"]
    U0210:
      train:
        - ["U0210", "S0300"]
      test:
        - ["U0210", "S0100"]
        - ["U0210", "S0200"]
        - ["U0210", "S0400"]
        - ["U0210", "S0500"]