errors:
- segments:
    boxes: -1
    session:
    - S0100
    streams:
    - e4-01
    - e4-02
  status: NO_FIX_AVAILABLE
  title: An error occurs when downloading data from E4 and this data is not available.
- segments:
    boxes: -1
    session:
    - S0100
    - S0200
    streams:
    - e4-02
  status: NO_FIX_AVAILABLE
  title: E4-02 was attached in the wrong direction.
- segments:
    boxes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    session:
    - S0200
    stream:
    - atr01
    - atr02
    - atr03
    - atr04
  status: PENDING
  title: ATR was turned off. Annotation process is suspended.
- segments:
    boxes: -1
    session:
    - S0500
    streams:
    - atr02
  status: NO_FIX_AVAILABLE
  title: ATR02 was attached in the wrong direction.
id: 201
meta:
  age_group: 20s
  dominant_hand: Right
  note: ''
  packaging_experience: None
  scenarios:
    S0100: S2
    S0200: S3
    S0300: S3
    S0400: S4
    S0500: S2
  sex: M
name: U0201
sessions:
  S0100:
    annotated_box: 20
    duration: 39m33s
    end: '2022-03-01T12:30:44+09:00'
    start: '2022-03-01T11:51:11+09:00'
  S0200:
    annotated_box: 12
    box:
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    duration: 22m26s
    end: '2022-03-01T14:40:25+09:00'
    start: '2022-03-01T14:17:59+09:00'
  S0300:
    annotated_box: 20
    duration: 36m14s
    end: '2022-03-01T16:03:26+09:00'
    start: '2022-03-01T15:27:12+09:00'
  S0400:
    annotated_box: 20
    duration: 28m18s
    end: '2022-03-15T15:54:20+09:00'
    start: '2022-03-15T15:26:02+09:00'
  S0500:
    annotated_box: 20
    duration: 25m27s
    end: '2022-03-22T15:37:15+09:00'
    start: '2022-03-22T15:11:48+09:00'
