kind: openpack/release
name: ${.metadata.labels.version}
metadata:
  labels:
    version: v1.0.0
    release: null
    urlZenodo: null
    urlGoogleDrive: null
    urlGoogleDriveRGB: null
spec:
  users:
    U0101:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - lidar/frames
      - kinect/color-masked/frames
    U0102:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - lidar/frames
      - kinect/color-masked/frames
    U0103:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0104:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      exclude:
      - kinect/color-masked/frames
    U0105:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0106:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0107:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0108:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0109:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0110:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0111:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0201:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0202:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0203:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0204:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0205:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
      exclude:
      - kinect/color-masked/frames
    U0206:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0207:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0208:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0209:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
    U0210:
      sessions:
      - S0100
      - S0200
      - S0300
      - S0400
      - S0500
  streams:
    zenodo:
    - annotation/openpack-actions
    - annotation/openpack-actions-1hz
    - annotation/openpack-operations
    - annotation/openpack-operations-1hz
    - annotation/openpack-outlier-events
    - atr/atr01
    - atr/atr02
    - atr/atr03
    - atr/atr04
    - e4/e401/acc
    - e4/e401/bvp
    - e4/e401/eda
    - e4/e401/temp
    - e4/e402/acc
    - e4/e402/bvp
    - e4/e402/eda
    - e4/e402/temp
    - kinect/2d-kpt/mmpose-hrnet-w48-posetrack18-384x288-posewarper-stage2/single
    - kinect/3d-kpt/none
    - kinect/3d-kpt/single-ffill-flip-fixed
    - system/order-sheet
    - system/ht
    - system/printer
    googleDrive:
    - kinect/depth/frames
    - rs02/depth/frames
    - lidar/frames
    googleDriveRGB:
    - kinect/color-masked/frames
